SweetSavory/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SweetSavory.Models
{
    public class Treat
    {
      public Treat()
      {
        this.JoinEntities = new HashSet<FlavorTreat>();
      }

      public int TreatId { get; set; }
      [Required(ErrorMessage = "A name is required.")]
      public string Name { get; set; }
      public virtual ICollection<FlavorTreat> JoinEntities { get; set; }
    }
}

SweetSavory/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using SweetSavory.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;

namespace SweetSavory.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly SweetSavoryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public FlavorsController(UserManager<ApplicationUser> userManager, SweetSavoryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Flavor> flavors = _db.Flavors.ToList();
      return View(flavors);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      if (ModelState.IsValid)
      {
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      return View(flavor);
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      List<Treat> currentTreats = new List<Treat> { };
      foreach (FlavorTreat join in thisFlavor.JoinEntities)
      {
        currentTreats.Add(join.Treat);
      }
      var availableTreats = _db.Treats.Where(treat => !currentTreats.Contains(treat)).ToList();
      ViewBag.TreatId = new SelectList(availableTreats, "TreatId", "Name");
      ViewBag.ValidItems = availableTreats.Any();
      return View(thisFlavor);
    }

    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      if (ModelState.IsValid)
      {
        _db.Entry(flavor).State = EntityState.Modified;
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = flavor.FlavorId });
      }
      return View(flavor);
    }

    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = flavor.FlavorId, TreatId = TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.FlavorId });
    }
  }
}

SweetSavory/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using SweetSavory.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;

namespace SweetSavory.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly SweetSavoryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public TreatsController(UserManager<ApplicationUser> userManager, SweetSavoryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Treat> treats = _db.Treats.ToList();
      return View(treats);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      if (ModelState.IsValid)
      {
        _db.Treats.Add(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      return View(treat);
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
        .Include(treat => treat.JoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      List<Flavor> currentFlavors = new List<Flavor> { };
      foreach (FlavorTreat join in thisTreat.JoinEntities)
      {
        currentFlavors.Add(join.Flavor);
      }
      var availableFlavors = _db.Flavors.Where(flavor => !currentFlavors.Contains(flavor)).ToList();
      ViewBag.FlavorId = new SelectList(availableFlavors, "FlavorId", "Name");
      ViewBag.ValidItems = availableFlavors.Any();
      return View(thisTreat);
    }

    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      if (ModelState.IsValid)
      {
        _db.Entry(treat).State = EntityState.Modified;
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = treat.TreatId });
      }
      return View(treat);
    }

    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.TreatId });
    }
  }
}

SweetSavory/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
  ViewData["Title"] = "Create Treat";
}

@model SweetSavory.Models.Treat

<div class="text-center">
  <h1 class="display-4">Create a Treat</h1>
</div>

<div class="center-form">
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    @Html.ValidationMessageFor(model => model.Name)
    <input type="submit" value="Add Treat" class="btn btn-dark">
  }
</div>

SweetSavory/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
  ViewData["Title"] = $"Deleting {@Model.Name}";
}

<div class="text-center">
  <h1 class="display-4">Deleting @Model.Name</h1>
</div>

<div class="delete">
  <p>Are you sure?</p>
  <hr>
  <div class="delete-buttons">
    @using (Html.BeginForm())
    {
      <input type="submit" value="Yes" class="btn btn-danger btn-lg" />
    }
    <a class="btn btn-success btn-lg" href="~/Treats/Details/@Model.TreatId">No</a>
  </div>
</div>

SweetSavory/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
  ViewData["Title"] = $"{@Model.Name} Details";
}

@model SweetSavory.Models.Treat

<div class="text-center">
  <h1 class="display-4">@Model.Name Details</h1>
  <p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>
</div>


@if (Model.JoinEntities.Count == 0)
{
  <p>No flavors have been assigned to this treat yet.</p>
}
else
{
  <p>This treat contains the following flavors:</p>
  <ul>
    @foreach (var join in Model.JoinEntities)
    {
      <div class="delete-join">
        <li>
          @Html.ActionLink($"{@join.Flavor.Name}", "Details", "Flavors", new { id = @join.Flavor.FlavorId })
          @if (User.Identity.IsAuthenticated)
          {
            @using (Html.BeginForm("DeleteFlavor", "Treats"))
            {
              @Html.Hidden("joinId", @join.FlavorTreatId)
              <input type="submit" value="Remove Flavor" class="btn btn-danger btn-sm">
            }
          }
        </li>
      </div>
    }
  </ul>
}

@if (User.Identity.IsAuthenticated)
{
  @if (ViewBag.ValidItems)
  {
    @using (Html.BeginForm("AddFlavor", "Treats"))
    {
      @Html.HiddenFor(model => model.TreatId)

      @Html.Label("Add Flavor")
      @Html.DropDownList("FlavorId")
      <input type="submit" value="Add Flavor" class="btn btn-dark btn-sm" />
    }
  }
  else
  {
    <p>This treat (somehow) contains all available flavors.</p>
  }
  <hr>
  <p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId})</p>
  <p>@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId})</p>
}

SweetSavory/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
  ViewData["Title"] = $"Editing {@Model.Name}";
}

@model SweetSavory.Models.Treat

<div class="text-center">
  <h1 class="display-4">Editing @Model.Name</h1>
</div>

<div class="center-form">
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TreatId)
    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)
    @Html.ValidationMessageFor(model => model.Name)
    <input type="submit" value="Edit Treat" class="btn btn-dark">
  }
</div>

SweetSavory/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
  ViewData["Title"] = "Treats";
}

@using SweetSavory.Models

<div class="text-center">
  <h1 class="display-4">Available Treats</h1>
</div>

@if (Model.Count == 0)
{
  <p>No treats have been added to the database yet.</p>
}
else
{
  <ul>
    @foreach (Treat treat in Model)
    {
      <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId })</li>
    }
  </ul>
}

@if(User.Identity.IsAuthenticated)
{
  @Html.ActionLink("Create a new treat", "Create")
}